=== eriksiegel/xtpxlib/xwebgen/xsd/xwebgen-specification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
  targetNamespace="http://www.xtpxlib.nl/ns/xwebgen" xmlns:xtlwg="http://www.xtpxlib.nl/ns/xwebgen">
  <xs:annotation>
    <xs:documentation>Schema for a xwebgen specification document. Such a document holds the instructions for the website generation by xwebgen.</xs:documentation>
  </xs:annotation>
  <xs:element name="xwebgen-specification">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="base-input-dir">
          <xs:annotation>
            <xs:documentation>The base input directory where the source contents resides.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:complexContent>
              <xs:extension base="xtlwg:ct-empty">
                <xs:attribute name="dref-source-dir" type="xtlwg:t-dref" use="required">
                  <xs:annotation>
                    <xs:documentation>Reference to the base input directory. Relative to the location of the specification file.</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attributeGroup ref="xtlwg:filter-attributes"/>
              </xs:extension>
            </xs:complexContent>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="base-output-dir">
          <xs:annotation>
            <xs:documentation>The base output directory where the results will be written. Will be cleaned beforehand!</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:complexContent>
              <xs:extension base="xtlwg:ct-empty">
                <xs:attribute name="dref-target-dir" type="xtlwg:t-dref" use="required">
                  <xs:annotation>
                    <xs:documentation>Reference to the base output directory. Relative to the location of the specification file.</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attributeGroup ref="xtlwg:filter-attributes"/>
              </xs:extension>
            </xs:complexContent>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="template">
          <xs:annotation>
            <xs:documentation>Specification of a template for the generation of the web pages.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:complexContent>
              <xs:extension base="xtlwg:ct-empty">
                <xs:attribute name="id" type="xtlwg:t-identifier" use="required">
                  <xs:annotation>
                    <xs:documentation>Identifier of this template</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="dref-source" type="xtlwg:t-dref" use="required">
                  <xs:annotation>
                    <xs:documentation>Document reference to the template XML document. Relative to the location of the base input directory.</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attributeGroup ref="xtlwg:filter-attributes"/>
              </xs:extension>
            </xs:complexContent>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" name="page">
          <xs:annotation>
            <xs:documentation>HTML pages to generate</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:group minOccurs="0" ref="xtlwg:g-properties"/>
            </xs:sequence>
            <xs:attribute name="template-idref" type="xtlwg:t-identifier" use="required">
              <xs:annotation>
                <xs:documentation>Identifier of the template to use to create this page.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="dref-section-document" type="xtlwg:t-dref" use="required">
              <xs:annotation>
                <xs:documentation>Reference to the xwebgen-sections document that holds the section to process for this page. Relative to the base input directory.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="section-idref" type="xtlwg:t-identifier">
              <xs:annotation>
                <xs:documentation>Identifier of the section to process. When absent the first section is taken.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
            <xs:attribute name="dref-target" type="xtlwg:t-dref" use="required">
              <xs:annotation>
                <xs:documentation>Document reference to result file. Relative to the location of the base output directory.</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="copy-dir">
          <xs:annotation>
            <xs:documentation>Directories to copy verbatim (e.g. for images and javascript)</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:complexContent>
              <xs:extension base="xtlwg:ct-empty">
                <xs:attribute name="dref-source-dir" type="xtlwg:t-dref" use="required">
                  <xs:annotation>
                    <xs:documentation>Reference to directory to copy. Relative to the base input directory.</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="dref-target-dir" type="xtlwg:t-dref">
                  <xs:annotation>
                    <xs:documentation>Reference to the output directory. Relative to the base output directory. When absent it is the same value as @dref-source-dir</xs:documentation>
                  </xs:annotation>
                </xs:attribute>
              </xs:extension>
            </xs:complexContent>
          </xs:complexType>
        </xs:element>
        <xs:group minOccurs="0" ref="xtlwg:g-properties"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:group name="g-properties">
    <xs:annotation>
      <xs:documentation>A list of properties that can be used in expanding the template and sections.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="properties">
        <xs:complexType>
          <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="property">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:string">
                    <xs:attribute name="id" type="xtlwg:t-identifier" use="required"/>
                    <xs:attributeGroup ref="xtlwg:filter-attributes"/>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:group>
  <xs:attributeGroup name="filter-attributes">
    <xs:annotation>
      <xs:documentation>Attributes in the xtlwg namespace are used for filtering the contents in this document</xs:documentation>
    </xs:annotation>
    <xs:anyAttribute namespace="http://www.xtpxlib.nl/ns/xwebgen" processContents="skip"/>
  </xs:attributeGroup>
  <xs:simpleType name="t-identifier">
    <xs:restriction base="xs:NCName"/>
  </xs:simpleType>
  <xs:simpleType name="t-dref">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>
  <xs:complexType name="ct-empty"/>
</xs:schema>

=== eriksiegel/xtpxlib/xwebgen/test/test-specification.xml
<?xml version="1.0" encoding="UTF-8"?>
<xwebgen-specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.xtpxlib.nl/ns/xwebgen ../xsd/xwebgen-specification.xsd" xmlns="http://www.xtpxlib.nl/ns/xwebgen"
  xmlns:xtlwg="http://www.xtpxlib.nl/ns/xwebgen">

  <base-input-dir xtlwg:lang="en" dref-source-dir="source-en"/>
  <base-input-dir xtlwg:lang="nl" dref-source-dir="source-nl"/>

  <base-output-dir xtlwg:lang="en" dref-target-dir="target-en"/>
  <base-output-dir xtlwg:lang="nl" dref-target-dir="target-nl"/>

  <template id="t1" dref-source="templates/template1.xml"/>

  <page dref-section-document="data/x1.xml" dref-target="x1.html" template-idref="t1">
    <properties>
      <property id="p1">TESTP1</property>
    </properties>
  </page>

  <copy-dir dref-source-dir="images"/>

  <properties>
    <property id="p1">TESTP1GLOBAL</property>
  </properties>

</xwebgen-specification>

=== eriksiegel/xtpxlib/xwebgen/test/source/website-xatapult-specification.xml
<?xml version="1.0" encoding="UTF-8"?>
<xwebgen-specification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.xtpxlib.nl/ns/xwebgen urn:x-xtpxlib.nl://xwebgen/xsd/xwebgen-specification.xsd"
  xmlns="http://www.xtpxlib.nl/ns/xwebgen" xmlns:xtlwg="http://www.xtpxlib.nl/ns/xwebgen"
  dref-base-output-dir="../../websites-generated/site-${lang}-${system}">

  <!-- ================================================================== -->
  <!--
    Main xwebgen specification file for the Xatapult website. Expects two filter parameters:
    - lang=nl or lang=en
    - system=PRD or system=TST
      TST will generate some other links to cater for the fact that the whole shebang is file based (and not served by a web-server)
  -->
  <!-- ================================================================== -->
  <!-- TEMPLATES: -->

  <template id="main" dref-source="templates/xatapult-main-page-template.xml"/>

  <!-- ================================================================== -->
  <!-- PAGES: -->

  <!-- Home page: -->
  <page template-idref="main" dref-section-document="data/sections-home.xml" section-idref="home" dref-target="home.html"/>

  <!-- Profile pages: -->
  <page template-idref="main" dref-section-document="data/sections-profile.xml" section-idref="page-about" dref-target="about.html"/>
  <page template-idref="main" dref-section-document="data/sections-profile.xml" section-idref="page-customers" dref-target="customers.html"/>
  <page template-idref="main" dref-section-document="data/sections-profile.xml" section-idref="page-services" dref-target="services.html"/>
  <page template-idref="main" dref-section-document="data/sections-profile.xml" section-idref="page-erik" dref-target="erik.html"/>

  <!-- Background pages: -->
  <page template-idref="main" dref-section-document="data/sections-background-information.xml" section-idref="page-content-engineering"
    dref-target="content-engineering.html"/>
  <page template-idref="main" dref-section-document="data/sections-background-information.xml" section-idref="page-xml" dref-target="xml.html"/>

  <!-- Publications: -->
  <page template-idref="main" dref-section-document="data/sections-publications.xml" section-idref="page-publications" dref-target="publications.html"/>

  <!-- Contact: -->
  <page template-idref="main" dref-section-document="data/sections-contact.xml" section-idref="page-contact" dref-target="contact.html"/>
  
  <!-- ================================================================== -->
  <!-- FIXED DIRECTORIES: -->

  <copy-dir dref-source-dir="images"/>
  <copy-dir dref-source-dir="css"/>
  <copy-dir dref-source-dir="js"/>
  <copy-dir dref-source-dir="resources"/>

  <!-- ================================================================== -->
  <!-- GLOBAL PROPERTIES: -->

  <properties>

    <!-- Default page title (override this for specific pages if necessary): -->
    <property id="page-title">Xatapult - Content Engineering</property>

    <!-- Phone and e-mail basics: -->
    <property id="phonenumber" xtlwg:lang="nl">06&#160;-&#160;53.26.07.92</property>
    <property id="phonenumber" xtlwg:lang="en">+31&#160;-&#160;6&#160;-&#160;53.26.07.92</property>
    <property id="email" xtlwg:lang="nl">info@xatapult.nl</property>
    <property id="email" xtlwg:lang="en">info@xatapult.com</property>

    <!-- Home links for TST: -->
    <property id="homelink" xtlwg:system="TST">home.html</property>
    <property id="homelink-other" xtlwg:lang="nl" xtlwg:system="TST">../site-en-TST/home.html</property>
    <property id="homelink-other" xtlwg:lang="en" xtlwg:system="TST">../site-nl-TST/home.html</property>

    <!-- Home links for PRD: -->
    <property id="homelink" xtlwg:lang="nl" xtlwg:system="PRD">http://www.xatapult.nl</property>
    <property id="homelink" xtlwg:lang="en" xtlwg:system="PRD">http://www.xatapult.com</property>
    <property id="homelink-other" xtlwg:lang="nl" xtlwg:system="PRD">http://www.xatapult.com</property>
    <property id="homelink-other" xtlwg:lang="en" xtlwg:system="PRD">http://www.xatapult.nl</property>

  </properties>

</xwebgen-specification>
